### PR TITLE
Fix encoding for metadata

### LINKED ISSUE #90: Wrong base64 encoding on multybyte utf-8 characters
While working on this SDK, we've found that if you use multibyte UTF8 chars in a `UnpublishedElection` object (either in the description or in any of the questions), the result is not coded properly.

I believe that the cause is this line, using "binary" as encoding.
https://github.com/vocdoni/vocdoni-sdk/blob/93dfae5a4bdac8641a8fb882669d448843b490b3/src/core/account.ts#L48

According to https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings, "binary" is an alias for "latin1".

I believe this should be using "utf8" instead. Otherwise we cannot use it for languages like Japanese.

### PR DESCRIPTION
**Pull request by microstudi**
fixes #90

### CODE REVIEW

**Comment by andreslucena** [comment]
We should probably add a regression test for this, probably on https://github.com/vocdoni/vocdoni-sdk/blob/main/test/integration/election.test.ts

**Comment by microstudi** [comment]
@elboletaire I've modified the test case. Can you run the workflow? thanks

**Comment by elboletaire** [comment]
The run is only triggering the `size` workflow... I'll have to change that.

**Comment by elboletaire** [comment]
Can you guys please rebase the code so the test files are reloaded and we can run the CI tests for the PR? I think we still need to figure out some issue related to this in the backend, but having the files updated would help.

**Comment by marcvelmer** [comment]
Fixed in #116

**Pull request closed without merging**
